version: '3.7'

services:
  web:
    build: ./.docker/
    environment:
      - PHP_IDE_CONFIG=serverName=magento2.dev.bfpg.hu
      - TERM=xterm
    hostname: magento2
    domainname: dev.bfpg.hu
    volumes:
      - ./:/var/www/dev/magento2
    labels:
      - traefik.enable=true
      - traefik.docker.network=bigfish_network
      - traefik.http.routers.magento.rule=Host(`magento2.dev.bfpg.hu`)
      - traefik.http.routers.magento.entrypoints=http
      - traefik.http.services.magento.loadbalancer.server.port=80
    networks:
      - local
      - bigfish_network
    extra_hosts:
      - host.docker.internal:host-gateway
    links:
      - db
      - mail
      - session
      - elasticsearch

  db:
    image: docker.pmgw.hu/development/mariadb
    command: --log-bin-trust-function-creators=1
    environment:
      - TERM=xterm
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=magento
      - MYSQL_PASSWORD=magento
      - MYSQL_DATABASE=magento
    networks:
      - local
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3309:3306

  mail:
    image: maildev/maildev
    container_name: magento_mail
    command: bin/maildev --web 80 --smtp 25
    networks:
      - local
      - bigfish_network
    labels:
      - traefik.enable=true
      - traefik.docker.network=bigfish_network
      - traefik.http.routers.magento-mail.rule=Host(`magento2-mail.dev.bfpg.hu`)
      - traefik.http.routers.magento-mail.entrypoints=http
      - traefik.http.services.magento-mail.loadbalancer.server.port=80

  session:
    image: docker.pmgw.hu/development/memcached
    networks:
      - local

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    #    ports:
    #      - 9200:9200
    #      - 9300:9300
    networks:
      - local

networks:

  local:
    name: local
    driver: bridge

  bigfish_network:
    external: true

volumes:
  db_data:
  elasticsearch-data:
    driver: local